### PR TITLE
Use app.render for all templates. Fixes #7

### LINKED ISSUE #7: Use app.render instead of templates.parse
We can get rid of this entirely: https://github.com/NodeBB/nodebb-widget-essentials/blob/master/library.js#L232-L250

Just use `app.render('widgets/recentreplies', {}, function(err, tpl) {` instead. Here is an example of the proper way of doing it: https://github.com/NodeBB/nodebb-widget-essentials/blob/master/library.js#L39-L53

### PR DESCRIPTION
**Pull request by yariplus**

### CODE REVIEW

**Comment by barisusakli** [comment]
Previously the code was loading the raw templates from admin/ now its storing parsed templates not sure if that's gonna break anything in the ACP page. @psychobunny

**Comment by yariplus** [comment]
ping @psychobunny

**Comment by barisusakli** [comment]
Did you guys test the admin page with this change?

**Comment by yariplus** [comment]
Works for me.:TM:

**Pull request merged**
